### ISSUE TITLE
Upload BOM excel.

### ISSUE THREAD

**Issue by Saxin** [8n1/ESP8266-Breakout-Adapter#1]
Hi,

Possible from your side to upload BOM excel for the boards ?

thanks, Eddi

**Comment by 8n1** [comment]
Hi, 
Documentations including BOM(Partlist) will be updated within the next days. 

John

**Comment by Saxin** [comment]
Thanks a lot.

**Comment by yannickgagne** [comment]
hey dude, just wanted to know if the BOM located here is the right one?

https://github.com/8n1/ESP8266-Breakout-Adapter/tree/master/Breakout%20Adapter%20v1.1%20-%20LM1117

And your work is awesome, thanks for sharing!!!

**Comment by 8n1** [comment]
Hi,
I've actually made 3 different versions but only version 1 (the one you've linked to) is really documented rigth now. 
Docs for version 2 and 3 will probably follow tomorrow. 

I just managed to take some pictures of all 3 versions:
Version 1: http://imgur.com/a/fsVE8
Version 2: http://imgur.com/a/XCGv0
Version 3: http://imgur.com/a/jSkG7

**Comment by yannickgagne** [comment]
Ok great!

I already ordered v1.1 and v3.0A from OSH Park, can't wait to order the parts and try them out.

Thanks again for your work.

**Comment by yannickgagne** [comment]
Hi,

just saw your update this morning and I just need your help for 2 components.

I would need to know the size of tact switch for the "ESP8266 Breakout v1.1 - x1117" board.

And what size is the slide switch used on "ESP Breakout Adapter v3.1A - AS1363 - Mini" board.

Thanks a lot!

**Comment by 8n1** [comment]
The used tact switch is a standard sized(6x6) one like this: 
http://www.ebay.at/itm/100Pcs-Tactile-Push-Button-Switch-Tact-Switch-6X6X5mm-4-pin-DIP-NEW-/181846910852
But you could also use one with just two pins like I did (the blue one on the pictures).

The slide switch I used is exactly this one:
www.ebay.at/itm/20PCS-Mini-Slide-Power-Off-On-Panel-PCB-MINI-SMD-Solder-Switch-SPM-/120731615109
I'm not sure about the exact part number but if you search for "mini slide switch smd" on ebay you'll find a lot of similar ones. 

If you have any further questions feel free to ask.

**Comment by yannickgagne** [comment]
Got some parts from Digikey today and wanted to let you know that the following slide switch fits perfectly if you want to add it to your BOM.

http://www.digikey.ca/product-search/en?keywords=CKN10374CT-ND

**Comment by 8n1** [comment]
Hey, thanks for the info! I will add it.

**Comment by yannickgagne** [comment]
Just wanted to let you know that I built a v1.1 last week and it works perfectly.

Will try the v3.1A soon.
