### ISSUE TITLE
assembly?

### ISSUE THREAD

**Issue by bebo-dot-dev** [8n1/ESP8266-Breakout-Adapter#2]
Fabulous work well done. Just one question really - are you able to say where it is that you're getting these boards assembled / soldered with the components listed in the BOM?

**Comment by yannickgagne** [comment]
I got the board from oshpark.com and the parts from digikey.com

**Comment by bebo-dot-dev** [comment]
It sounds like you're assembling and soldering all components on yourself. Is that right?

**Comment by yannickgagne** [comment]
yes
